#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Archive-Cpio
Version  : 0.10
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/P/PI/PIXEL/Archive-Cpio-0.10.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PI/PIXEL/Archive-Cpio-0.10.tar.gz
Source1  : http://http.debian.net/debian/pool/main/liba/libarchive-cpio-perl/libarchive-cpio-perl_0.10-1.debian.tar.xz
Summary  : 'module for manipulations of cpio archives'
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Archive-Cpio-bin
Requires: perl-Archive-Cpio-license
Requires: perl-Archive-Cpio-man

%description
No detailed description available

%package bin
Summary: bin components for the perl-Archive-Cpio package.
Group: Binaries
Requires: perl-Archive-Cpio-license
Requires: perl-Archive-Cpio-man

%description bin
bin components for the perl-Archive-Cpio package.


%package license
Summary: license components for the perl-Archive-Cpio package.
Group: Default

%description license
license components for the perl-Archive-Cpio package.


%package man
Summary: man components for the perl-Archive-Cpio package.
Group: Default

%description man
man components for the perl-Archive-Cpio package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Archive-Cpio-0.10
mkdir -p %{_topdir}/BUILD/Archive-Cpio-0.10/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Archive-Cpio-0.10/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Archive-Cpio
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Archive-Cpio/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Archive/Cpio.pm
/usr/lib/perl5/site_perl/5.26.1/Archive/Cpio/Common.pm
/usr/lib/perl5/site_perl/5.26.1/Archive/Cpio/File.pm
/usr/lib/perl5/site_perl/5.26.1/Archive/Cpio/FileHandle_with_pushback.pm
/usr/lib/perl5/site_perl/5.26.1/Archive/Cpio/NewAscii.pm
/usr/lib/perl5/site_perl/5.26.1/Archive/Cpio/ODC.pm
/usr/lib/perl5/site_perl/5.26.1/Archive/Cpio/OldBinary.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/cpio-filter

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Archive-Cpio/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/cpio-filter.1
/usr/share/man/man3/Archive::Cpio.3
